name: Test (PHP)

on:
  push:
    branches: [ master ]
  pull_request:
    paths: [ '**.php' ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-clover clover.xml
    
    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: vendor/bin/php-coveralls --coverage_clover=clover.xml -v
